### ISSUE TITLE
docker fastdeployserver 启动失败 CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by kerry-weic** [PaddlePaddle/FastDeploy#1745]
## 环境

- 【FastDeploy版本】： docker pull registry.baidubce.com/paddlepaddle/fastdeploy:1.0.4-gpu-cuda11.4-trt8.5-21.10
- 【编译命令】如果您是自行编译的FastDeploy，请说明您的编译方式（参数命令）
- 【系统平台】: Linux x64(Ubuntu 18.04) / Windows x64(Windows10) / Mac OSX arm(12.0) / Mac OSX intel(12.0)
- 【硬件】： NVIDIA RTX A4000，CUDA 11.7
- 【编译语言】： C++ / Python(3.7或3.8等）
参考文档启动服务失败:
https://github.com/PaddlePaddle/PaddleOCR/tree/dygraph/deploy/fastdeploy/serving/fastdeploy_serving#33-%E5%90%AF%E5%8A%A8%E6%9C%8D%E5%8A%A1%E7%AB%AF%E5%9C%A8docker%E5%86%85

报错原因是因为我使用镜像包cuda版本为11.4？

报错日志片段如下，
rror: Failed to initialize NVML
W0330 07:24:49.642447 370 metrics.cc:221] DCGM unable to start: DCGM initialization error
W0330 07:24:49.643144 370 pinned_memory_manager.cc:236] Unable to allocate pinned system memory, pinned memory pool will not be available: **CUDA driver version is insufficient for CUDA runtime version**
I0330 07:24:49.643227 370 cuda_memory_manager.cc:115] CUDA memory pool disabled
E0330 07:24:49.645021 370 model_repository_manager.cc:1890] Poll failed for model directory 'cls_runtime': instance group cls_runtime_0 of model cls_runtime specifies invalid or unsupported gpu id 0. GPUs with at least the minimum required CUDA compute compatibility of 6.000000 are: 
E0330 07:24:49.645423 370 model_repository_manager.cc:1890] Poll failed for model directory 'det_runtime': instance group det_runtime_0 of model det_runtime specifies invalid or unsupported gpu id 0. GPUs with at least the minimum required CUDA compute compatibility of 6.000000 are: 
E0330 07:24:49.646024 370 model_repository_manager.cc:1890] Poll failed for model directory 'rec_runtime': instance group rec_runtime_0 of model rec_runtime specifies invalid or unsupported gpu id 0. GPUs with at least the minimum required CUDA compute compatibility of 6.000000 are: 
E0330 07:24:49.646119 370 model_repository_manager.cc:1375] Invalid argument: ensemble rec_pp contains models that are not available: rec_runtime
E0330 07:24:49.646143 370 model_repository_manager.cc:1375] Invalid argument: ensemble pp_ocr contains models that are not available: det_runtime
E0330 07:24:49.646156 370 model_repository_manager.cc:1375] Invalid argument: ensemble cls_pp contains models that are not available: cls_runtime

**Comment by a0735a** [comment]
@kerry-weic 解决了吗？我也遇到同样的问题

**Comment by kerry-weic** [comment]
@a0735a  没，现在暂时用simple deploy gpu版本运行，当时尝试过fast deploy cpu的镜像包可以用，后续要是解决了期待分享其方案。

**Comment by teymur-git** [comment]
@kerry-weic 确认显卡驱动为    >=11.4 ，<12.0
